# Generated by Django 2.2.8 on 2019-12-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Differentiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=150)),
                ('function', models.TextField()),
                ('differentiation', models.TextField()),
                ('graph', models.FileField(default=None, upload_to='')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
