# Generated by Django 2.2.8 on 2019-12-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='differentiation',
            old_name='data',
            new_name='date',
        ),
        migrations.AddField(
            model_name='differentiation',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
