# Generated by Django 2.2.8 on 2020-01-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20191225_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exstrapolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=150)),
                ('dots', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('extrapolation', models.TextField()),
                ('graph', models.FileField(default=None, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='differentiation',
            name='order',
            field=models.IntegerField(),
        ),
    ]
